spring:
  application:
    name: schedule-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      lease-renewal-interval-in-seconds: 10  # Renewal every 10 seconds (adjust as needed)
      lease-expiration-duration-in-seconds: 30  # Expire after 30 seconds without renewal

